### ISSUE TITLE
The best way to add injection

### ISSUE THREAD

**Issue by tossnet** [Apps72/BlazorGuidelines#1]
I always wonder where to put my injections... 

1. in the RAZOR page (@inject ...) 
2. in the partial class ([injec] ... 

What is your opinion?

**Comment by dvoituron** [comment]
In my opinion, I prefer to put all the code in the "Code Behind" file. 
And therefore, **to put the injection in the .cs**.
The .razor is only used for the design part and the layout of this HTML design (via loops and Razor tests)

**Comment by dvoituron** [comment]
Do you inject in private or public properties?
- `private Factory Factory { get; set; }`
- `public Factory Factory { get; set; }`

**Comment by tossnet** [comment]
in my case, all in private

**Comment by dvoituron** [comment]
So, a best practice will be

```csharp
[Inject]
private IMemoryCache MemoryCache { get; set; }
```

**Comment by tossnet** [comment]
strangely, I don't like the BR  ^^ 
![image](https://user-images.githubusercontent.com/3845786/133758592-13e39489-c2e6-44d2-a633-350841885454.png)
and you ?

**Comment by dvoituron** [comment]
In my best practices, all attributes **are above** of the property/method... so, including [Inject]
The first reason is, because you can have multiple attributes : serialization, authorizations, decoration, injection, ...

**Comment by tossnet** [comment]
OK, Right !  I'll change my code
I need to use #REGION now... :/ 
![image](https://user-images.githubusercontent.com/3845786/133760123-754e0259-913b-4ce9-8a48-9ea55b9ed0b9.png)

**Comment by dvoituron** [comment]
It's for this reason, I'm using a _Factory pattern_ to include all service references into a **Factory** class.
So, in my component / page, when I need to use a service of my project, I inject `Factory` and I use the property `Factory.Profiles`.

Factory class
```csharp
public virtual ProfileService Profiles => _profileService ?? (_profileService = new ProfileService(this));

public virtual AccountingService Accounting => _accountingService ?? (_accountingService = new AccountingService(this));
```

If the service is provided my Microsoft or external library, I inject the service directly to my component.
The Factory is used only for **my** services.
