### ISSUE TITLE
Abuse of CSS isolation

### ISSUE THREAD

**Issue by tossnet** [Apps72/BlazorGuidelines#4]
It seems preferable to use as much as possible a css / .razor

**Comment by iso8859** [comment]
Css isolation is only interesting on small HTML fragment.
When you use it an attribute is added in every HTML tag.
For example

    <table b-uvsbxoi8u9=""><colgroup b-uvsbxoi8u9=""> ...

If you generate a lot of HTML this attribute bloat your page.

**Comment by tossnet** [comment]
Yes I know how it works, and I'm not convinced that it affects performance.

Before this existed, in a project with 20 razor components, these global CSS styles were very complex to manage and to find in the solution.

If there is a small loss of performance (I didn't see it at all), then there is a big gain in the project.

Another problem is when customizing the CSS of the UI framework used;  This implies to use globally !IMPORTANT :/ Locally it is often more convenient .
