### ISSUE TITLE
Blazor Server vs Blazor Web Assembly

### ISSUE THREAD

**Issue by iso8859** [Apps72/BlazorGuidelines#8]
Blazor is a great product for C# developper
- Don't need to learn Javascript but you need to learn HTML and CSS.
- You can begin to be efficient in a week if you are already a senior C# dev.
- Reopen the project 6 month later, because it's C# you will find your marks very quickly.
- No dependencies. Install Visual Studio, code, debug, build, test, deploy.

Blazor Server App (BSA)
- Compatible with all web browsers.
- Great for intranet develoment or MVP (Minimum Viable Product) because you develop fast.
- A big server can handle up to 5000 concurent connection.
- Be carefull about processor you need on complex page.
- You can scale on several server but you need to create a "login server" that will load balance the user on the other servers.
- Awesome if you don't need the expose some API because you don't need to create API. A real time saver on huge project.
- Also awesome for debugging from Visual Studio, you debug web like WinForm.
- All your connection strings stay on the server.

Blazor WebAssembly (BWA)
- Works only with lastest web browsers. Need to download the WebAssembly that is not very light.
- Great for CPU intensive app that will run on the client side...
- ...but this mean the algorithm can be reverse engineered.
- You need to develop API. gRPC is also a solution that can be use both for gRPC protocol and REST (gRPC definition file is the reference and create C# classes. This definition file is a big time saver for team development : front / back).
- If your app is API intensive you need to handle this scalability with a load balancing mecanism.
- You can debug with Visual Studio but this is not very fluid.
- Difficult to call cloud services from client because connection string can be revealed.

You can develop project that can target both BSA and BWA

**Comment by dvoituron** [comment]
Hello,
Why this comparison, in a Guideline? 
Are you recommending good practices?
